version: "3.8"

services:
  app:
    image: node:22
    container_name: my-node-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run start"
